title: World of Mina
description: >-
  Guide personnel pour créer un action-RPG en pixel art avec Godot Engine.
  Notes pas à pas, de Mina qui marche jusqu'aux fondations d'un monde entier.
theme: jekyll-theme-cayman
show_downloads: false

# Métadonnées
lang: fr
author: Lysdora
